<a href="https://colab.research.google.com/github/ASO1801006/AI_teach2020/blob/master/20201009AI0205_selectAlgo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### sklearnでエラーがでるので、前のバージョンを入れ直す

In [2]:
##　現在のscikit-learnをアンインストール
#!pip uninstall scikit-learn
## 前のバージョンを指定してVMにインストール
#!pip install scikit-learn==0.20 --ignore-installed

### all_estimators()でループして各種のアルゴリズムで学習させ、比較する

In [3]:
# ライブラ
import pandas as pd
# 学習用デーテスト検証用データを分割するライブラリ
from sklearn.model_selection import train_test_split
# 正解率を算出するライブラリ
from sklearn.metrics import accuracy_score
# all_estimaors(推定器の全てを利用できるようにする)
from sklearn.utils.testing import all_estimators
# 警告クラス
import warnings

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.utils.testing module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.utils. Anything that cannot be imported from sklearn.utils is now part of the private API.
  warnings.warn(message, FutureWarning)


### webからアヤメのデータを読み込む

In [4]:
# urlリンクから読み込むライブラリ
import urllib.request as req
#　url用の文字列変数を定義
url = "https://raw.githubusercontent.com/pandas-dev/pandas/master/pandas/tests/io/data/csv/iris.csv"
# リンクから保存するためのファイル名を定義
savefile = "iris.csv"
# requestクラスを使ってurlからデータをsavefileへコピーして保存
req.urlretrieve(url, savefile)
# pandasのread_csvメソッドを使ってCSVファイルを読み込む
iris_data = pd.read_csv(savefile, encoding="utf-8")
iris_data.head()

SepalLength  SepalWidth  PetalLength  PetalWidth         Name
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

### アヤメデータを目的変数:y(ラベル)と説明変数:x(入力データ)に分類する

In [5]:
y = iris_data.loc[:,"Name"] # 目的変数
x = iris_data.loc[:, ["SepalLength","SepalWidth","PetalLength","PetalWidth"]] # 説明変数

print(y.head())
print(x.head())

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: Name, dtype: object
   SepalLength  SepalWidth  PetalLength  PetalWidth
0          5.1         3.5          1.4         0.2
1          4.9         3.0          1.4         0.2
2          4.7         3.2          1.3         0.2
3          4.6         3.1          1.5         0.2
4          5.0         3.6          1.4         0.2


### アヤメデータをさらに学習用とテスト検証用に分類する

In [6]:
# 学習データ(train)とテスト検証用(test)に分類
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, train_size=0.8, shuffle=True)
print(x_train)
print(x_test)
print(y_train)
print(y_test)

     SepalLength  SepalWidth  PetalLength  PetalWidth
127          6.1         3.0          4.9         1.8
74           6.4         2.9          4.3         1.3
22           4.6         3.6          1.0         0.2
123          6.3         2.7          4.9         1.8
112          6.8         3.0          5.5         2.1
..           ...         ...          ...         ...
93           5.0         2.3          3.3         1.0
108          6.7         2.5          5.8         1.8
59           5.2         2.7          3.9         1.4
144          6.7         3.3          5.7         2.5
85           6.0         3.4          4.5         1.6

[120 rows x 4 columns]
     SepalLength  SepalWidth  PetalLength  PetalWidth
111          6.4         2.7          5.3         1.9
100          6.3         3.3          6.0         2.5
70           5.9         3.2          4.8         1.8
41           4.5         2.3          1.3         0.3
63           6.1         2.9          4.7         1.4
87  

### allAlgorithmsにclassifierを指定して「分類」でフィルターしたアルゴリズムの推定器群を取得する

In [7]:
# 推定器のリストをフィルター指定して取得
allAlgorithms = all_estimators(type_filter="classifier")
# ワーニングを無視する
warnings.filterwarnings("ignore")

/usr/local/lib/python3.6/dist-packages/sklearn/externals/joblib/__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)


##＃ 推定器のリストをループしながら学習&推論させる

In [8]:
# 推定器のリストをループ
for (name, algorithm) in allAlgorithms:

# pythonでのtry-catch(try-except)
  try: # pythonのtry
  # 各アルゴリズムのオブジェクトを生成 
    clf = algorithm() # 各アルゴリズムクラスのコンストラクタを実行
    #  学習させる(fitメソッド)
    clf.fit(x_train, y_train)
    # 推論する
    y_pred = clf.predict(x_test)
    # accuracy_scoreで正解率を算出して表示する
    print( name, "の正解率 = ", accuracy_score(y_test, y_pred))
    # tryの終わり
    # pythonのcatch(except)
  except Exception as e: # pythonのcatch(except)
    print("¥033[31m", "Error: ¥033[0m", name ,":", e.args)
  else: 
    print("エラー以外")
    # try-catchの終了
  # for文の終了

# for文終了


AdaBoostClassifier の正解率 =  0.9
エラー以外
BaggingClassifier の正解率 =  0.9
エラー以外
BernoulliNB の正解率 =  0.3
エラー以外
CalibratedClassifierCV の正解率 =  0.8666666666666667
エラー以外
CategoricalNB の正解率 =  0.9666666666666667
エラー以外
¥033 Error: ¥033 CheckingClassifier : ("could not convert string to float: 'Iris-virginica'",)
¥033 Error: ¥033 ClassifierChain : ("__init__() missing 1 required positional argument: 'base_estimator'",)
ComplementNB の正解率 =  0.7
エラー以外
DecisionTreeClassifier の正解率 =  0.9
エラー以外
DummyClassifier の正解率 =  0.3
エラー以外
ExtraTreeClassifier の正解率 =  0.9333333333333333
エラー以外
ExtraTreesClassifier の正解率 =  0.9
エラー以外
GaussianNB の正解率 =  0.8666666666666667
エラー以外
GaussianProcessClassifier の正解率 =  0.9333333333333333
エラー以外
GradientBoostingClassifier の正解率 =  0.9
エラー以外
HistGradientBoostingClassifier の正解率 =  0.9
エラー以外
KNeighborsClassifier の正解率 =  0.9333333333333333
エラー以外
LabelPropagation の正解率 =  0.9
エラー以外
LabelSpreading の正解率 =  0.9
エラー以外
LinearDiscriminantAnalysis の正解率 =  0.9333333333333333
エラー以外
LinearSVC の正解率

### クロスバリデーション

### クロスバリデーション関連のライブラリのインポート

In [9]:
# ライブラリのインポート
# K分割クロスバリデーション(交差検証)のためのライブラリ
from sklearn.model_selection import KFold
# クロスバリデーションスコア
from sklearn.model_selection import cross_val_score


### クロスバリデーションを実行する

In [10]:
# K分割交差検証のインスタンスを生成する
kfold_cv = KFold(n_splits=5, shuffle=True)
# 既に生成してあるall_estimatorsのインスタンスをループさせてクロスバリデーションを行う
for (name, algorithm) in allAlgorithms:
  try:
    #　各アルゴリズムのインスタンスを取得
    うjk
    # scoreの属性がある学習モデルだけに絞る
    if hasattr(clf, "score"):
      # クロスバリデーション(をしてスコアを取得する
      score = cross_val_score(clf, x, y, cv=kfold_cv)
      # k=n_split=5回分のクロスバリデーションのスコア表示
      print(name, "の正解率 = ")
      print(score)
      #ifブロック終了
    # tryブロック終了
  except Exception as e: # 例外処理ブロック
    #　何もしない
    print(e.args)
    # pass

("name 'うjk' is not defined",)
("name 'うjk' is not defined",)
("name 'うjk' is not defined",)
("name 'うjk' is not defined",)
("name 'うjk' is not defined",)
("name 'うjk' is not defined",)
("name 'うjk' is not defined",)
("name 'うjk' is not defined",)
("name 'うjk' is not defined",)
("name 'うjk' is not defined",)
("name 'うjk' is not defined",)
("name 'うjk' is not defined",)
("name 'うjk' is not defined",)
("name 'うjk' is not defined",)
("name 'うjk' is not defined",)
("name 'うjk' is not defined",)
("name 'うjk' is not defined",)
("name 'うjk' is not defined",)
("name 'うjk' is not defined",)
("name 'うjk' is not defined",)
("name 'うjk' is not defined",)
("name 'うjk' is not defined",)
("name 'うjk' is not defined",)
("name 'うjk' is not defined",)
("name 'うjk' is not defined",)
("name 'うjk' is not defined",)
("name 'うjk' is not defined",)
("name 'うjk' is not defined",)
("name 'うjk' is not defined",)
("name 'うjk' is not defined",)
("name 'うjk' is not defined",)
("name 'うjk' is not defined",)
("name '

### おまけ：cross_val_scoreよりも、もっと詳しい結果を取得できる新しいクロスバリデーションオブジェクト：cross_validate

In [11]:
# ライブラリのインポート
from sklearn.model_selection import cross_validate

### cross_validateを使ったクロスバリデーション

In [12]:
# K分割交差検証のインスタンスを生成する
kfold_cv = KFold(n_splits=5, shuffle=True)
# 既に生成してあるall_estimatorsのインスタンスをループさせてクロスバリデーションを行う
for (name, algorithm) in allAlgorithms:
  try:
    #　各アルゴリズムのインスタンスを取得
    clf = algorithm()
    # scoreの属性がある学習モデルだけに絞る
    if hasattr(clf, "score"):
      # クロスバリデーション(をしてスコアを取得する
      score = cross_validate(clf, x, y, cv=kfold_cv)
      # k=n_split=5回分のクロスバリデーションのスコア表示
      print(name, "の正解率 = ")
      print(score)
      #ifブロック終了
    # tryブロック終了
  except Exception as e: # 例外処理ブロック
    #　何もしない
    print(e.args)
    # pass

AdaBoostClassifier の正解率 = 
{'fit_time': array([0.07726955, 0.06584716, 0.06640196, 0.07171893, 0.07701755]), 'score_time': array([0.00726652, 0.00700259, 0.00681639, 0.00822973, 0.01406693]), 'test_score': array([0.9       , 0.96666667, 0.9       , 0.93333333, 1.        ])}
BaggingClassifier の正解率 = 
{'fit_time': array([0.01650238, 0.01516557, 0.0153923 , 0.01527619, 0.01507187]), 'score_time': array([0.0022912 , 0.00226212, 0.00216866, 0.00260329, 0.00215507]), 'test_score': array([0.9       , 1.        , 0.93333333, 0.96666667, 0.96666667])}
BernoulliNB の正解率 = 
{'fit_time': array([0.00312233, 0.00281644, 0.00277328, 0.00291848, 0.00277734]), 'score_time': array([0.00134659, 0.00129032, 0.0014894 , 0.00136638, 0.00159025]), 'test_score': array([0.3       , 0.26666667, 0.26666667, 0.26666667, 0.3       ])}
CalibratedClassifierCV の正解率 = 
{'fit_time': array([0.06416512, 0.07217979, 0.05701137, 0.05794573, 0.05638528]), 'score_time': array([0.002069  , 0.00209093, 0.00181317, 0.00180769, 0

：

### グリッドサーチで最適なパラメータを探し求める

### ライブラリをimport

In [13]:
# グリッドサーチのオブジェクトクラsうをimport
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC

### グリッドサーチを実行したパラメータを試す

In [14]:
# グリッドサーチで試すパラメータのパターン指定を定義する
parameters = [
              # ３つのパラメータ,３パターン
              {"C":[1, 10, 100, 1000], "kernel":["linear"]},
              {"C":[1, 10, 100, 1000], "kernel":["rbf"], "gamma":[0.001, 0.0001]},
              {"C":[1, 10, 100, 1000], "kernel":["sigmoid"], "gamma":[0.001, 0.0001]},
]
#　普通の学習
clf = SVC()
clf.fit(x_train, y_train)
y_pred = clf.predict(x_test)
print("普通の学習の正解率 = ", accuracy_score(y_test, y_pred))

# グリッドサーチを行う
# K分割交差検証用のインスタンスを生成する
kfold_cv = KFold(n_splits=5, shuffle=True)
# グリッドサーチの中でK分割交差検証も行われる
clf_grid = GridSearchCV(SVC(), parameters, cv=kfold_cv)
clf_grid.fit(x_train, y_train) # 学習
# 学習済みのモデルに最終的に設定された(最適と思われる)パラメータを表示
print("最適なパラメーター = ", clf_grid.best_estimator_)

#　最適なパラメータ設定済みの学習モデルで評価
y_pred = clf_grid.predict(x_test)
print("グリッドサーチの正解率 = ", accuracy_score(y_test, y_pred))

普通の学習の正解率 =  0.9333333333333333
最適なパラメーター =  SVC(C=1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)
グリッドサーチの正解率 =  0.9333333333333333


### Numpyの動作確認

In [15]:
# import
import numpy as np

In [16]:
#　numpy配列の初期化
a = np.array([1, 2, 3, 4, 5]) # ndarray配列
print(a)
# type関数で型を表示
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [17]:
# 2次元のndarrayを定義
b = np.array([[1, 2, 3],[4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [18]:
# 配列の要素数を指定して０埋めて初期化
print(np.zeros(10))
print(np.zeros((3, 2)))
print(np.ones(2))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[1. 1.]


In [19]:
# 連番の配列を要素数を指定して初期化
print(np.arange(5)) # 0から５未満
print(np.arange(2, 9)) # 2から9未満
print(np.arange(5, 8, 0.5)) #　５から８未満　0.5間隔

[0 1 2 3 4]
[2 3 4 5 6 7 8]
[5.  5.5 6.  6.5 7.  7.5]


###　numpyで行列計算

In [20]:
a = np.array([1, 2, 3, 4, 5])
b = 2 * a # 全ての要素を一度に2倍
print(b)
x = np.arange(10)
y = 3 * x + 5 # 全ての要素を一度の四則演算
print(y)

[ 2  4  6  8 10]
[ 5  8 11 14 17 20 23 26 29 32]


In [21]:
#　配列の次元数を表示
a = np.array([[1, 2, 3],[4, 5, 6]])
print(a)
print(a.shape)

b = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(b)
print(b.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [22]:
# Numpy配列で次元数を変換する
a = np.array([[1, 2, 3],[4, 5, 6]])
print("a=",a )
b = a.flatten()
print("b=",b)

a = np.array([[1, 2, 3],[4, 5, 6]]) # 2行列
print(a)
b = a.reshape(3,2) # 3行2列に変換(回転)する
print(b)

a= [[1 2 3]
 [4 5 6]]
b= [1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


### numpyの配列にアクセスする方法

In [25]:
v = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
a = v[0]
print(a) # 2次元配列の0行目
b = v[1:]
print(b) # 1行目以降
c = v[:, 0]
print(c) # 全ての行の0列目

[1 2 3]
[[4 5 6]
 [7 8 9]]
[1 4 7]
